version: 2
jobs:
  build:
    docker:
      - image: massiveco/docker-alpine-sdk
    steps:
      - checkout
      - run:
        name: Build testing packages
        command: make testing
      - persist_to_workspace:
          root: /tmp
          paths:
            - packages
  deploy:
    machine: true
    steps:
      - attach_workspace:
        at: /tmp
      - apt add awscli
      - aws s3 sync /tmp/packages s3://alpine.ma.ssive.co --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master