version: 2
jobs:
  build:
    docker:
      - image: massiveco/docker-alpine-sdk
    steps:
      - checkout
      - run: make testing
      - persist_to_workspace:
          root: /tmp
          paths:
            - packages
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp
      - run: apt add awscli
      - run: aws s3 sync /tmp/packages s3://alpine.ma.ssive.co --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master