version: 2
jobs:
  build:
    docker:
      - image: massiveco/docker-alpine-sdk
    steps:
      - checkout
      - run:
          name: Build testing packages
          command: make testing
      - store_artifacts:
            path: /tmp/packages